#ifndef WEBKITBROWSER_GLOBAL_H
#define WEBKITBROWSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBKITBROWSER_LIBRARY)
#  define WEBKITBROWSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBKITBROWSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBKITBROWSER_GLOBAL_H
